name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v4

      - name: Create release zip
        run: |
          cd custom_components
          zip -r ../airseekers_tron.zip airseekers_tron

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./airseekers_tron.zip
          asset_name: airseekers_tron.zip
          asset_content_type: application/zip
